name: Generate Javadoc
on: [workflow_dispatch]

jobs:
  javadoc:
    name: Generate Javadoc
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Prepate Git Repo
        uses: actions/checkout@v2.3.4

      - name: ☕ Install Java
        uses: actions/setup-java@v2.3.0
        with:
          architecture: x64
          distribution: temurin
          java-version: 11

      - name: 📦 Package with Maven
        run: mvn package -Dmaven.test.skip=true

      - name: 📦 Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: javadoc
          path: target/*-javadoc.jar