name: Java CI
on:
  push: {}
  pull_request:
    branches: [main]
permissions: read-all

jobs:
  java_ci:
    name: Java CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [8, 9, 11, 16]
      fail-fast: false
    env:
      INPUT_INPUT: 'val'
      INPUT_SPECIAL_CHARS: "'	\"\\ response "
      INPUT_MULTIPLE_SPACE_VARIABLE: 'I have multiple spaces'
      INPUT_MULTIPLE_LINES: |
        val1
        val2
        val3
      INPUT_WHITESPACE: '  some val  '
      INPUT_BOOLEAN: 'true'
      INPUT_TRUE1: 'true'
      INPUT_TRUE2: 'True'
      INPUT_TRUE3: 'TRUE'
      INPUT_FALSE1: 'false'
      INPUT_FALSE2: 'False'
      INPUT_FALSE3: 'FALSE'
      INPUT_WRONG: 'wrong'
      STATE_TEST_1: 'state_val'

    steps:
      - name: 📦 Prepare Git Repo
        uses: actions/checkout@v2.3.4

      - name: ☕ Install OpenJDK
        uses: AdoptOpenJDK/install-jdk@v1.1.1
        with:
          version: ${{ matrix.jdk }}
          architecture: x64

      - name: 📤 Load Cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - id: mvn
        name: ✔ Test with Maven
        run: mvn test -fae --no-transfer-progress

      - name: ✔ Test Output
        if: steps.mvn.outputs['some output'] != '1.01' && steps.mvn.outputs['some output'] != 'false' && steps.mvn.outputs['some output'] != 'some value'
        run: |
          echo "::set-failed::Output is missing"
          exit 1