name: Deploy to Maven Central

on:
  release:
    types: [published]

jobs:
  java_ci:
    name: Java CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [8, 9, 11, 16]
      fail-fast: false
    steps:
      - name: 📤 Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: 📚 Install OpenJDK
        uses: AdoptOpenJDK/install-jdk@v1.1.1
        with:
          version: ${{ matrix.jdk }}
          architecture: x64

      - name: 📦 Compile with Maven
        run: mvn compile -Dmaven.test.skip=true --no-transfer-progress

  deploy:
    name: Deploy to Maven Central
    runs-on: ubuntu-latest
    environment: Maven Central
    needs: java_ci
    steps:
      - name: 📚 Install OpenJDK
        uses: AdoptOpenJDK/install-jdk@v1.1.1

      - name: 🔐 Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3.1.0
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: ☕ Install OpenJDK
        uses: AdoptOpenJDK/install-jdk@v1.1.1
        with:
          version: '11'
          architecture: x64

      - name: 🚀 Deploy to Maven
        run: mvn -B deploy -f pom.xml -s settings.xml -P deploy
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

      - name: 🚀 Deploy to Releases
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'target/*.jar'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
