name: Sample with JCore
on:
  push: {}
  pull_request:
    branches: [main]
permissions: read-all

jobs:
  java:
    name: Java (JCore Enabled = ${{ matrix.sample }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        sample: [true]
    env:
      sample_only: ${{ matrix.sample }}
    steps:
      - name: 📤 Checkout Repository
        uses: actions/checkout@v2.4.0

      - name: ☕ Install Java
        uses: actions/setup-java@v2.5.0
        with:
          architecture: x64
          distribution: temurin
          java-version: 17

      - id: mvn
        name: ✔ Test with Maven
        continue-on-error: true
        run: |
          mvn test -fae --no-transfer-progress