name: Sample [Before]
on:
  push: {}
  pull_request:
    branches: [main]
permissions: read-all

jobs:
  java:
    name: java
    runs-on: ubuntu-latest
    env:
      sample_only: false

    steps:
      - name: 📦 Prepare Git Repo
        uses: actions/checkout@v2.3.4

      - name: ☕ Install Java
        uses: actions/setup-java@v2.3.0
        with:
          architecture: x64
          distribution: temurin
          java-version: 11

      - id: mvn
        name: ✔ Test with Maven
        continue-on-error: true
        run: |
          mvn test -fae --no-transfer-progress