name: Sample [After]
on:
  push: {}
  pull_request:
    branches: [main]
permissions: read-all

jobs:
  java:
    name: java
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      sample_only: true

    steps:
      - name: 📤 Checkout Repository
        uses: actions/checkout@v2.3.5

      - name: ☕ Install Java
        uses: actions/setup-java@v2.3.1
        with:
          architecture: x64
          distribution: temurin
          java-version: 17

      - id: mvn
        name: ✔ Test with Maven
        continue-on-error: true
        run: |
          mvn test -fae --no-transfer-progress