name: temp
on:
  push: {}
  pull_request:
    branches: [main]
permissions: read-all

jobs:
  temp:
    name: temp
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Prepate Git Repo
        uses: actions/checkout@v2.3.4

      - name: 📋 Preload Env
        run:
            echo "::warning file=src/main/java/com/kttdevelopment/jcore/Workflow.java,line=10,col=1::warning"
